on:
  push:
    branches:
      - main
      - master
    paths: .github/workflows/bookdown-rsconnect-build.yaml
  workflow_dispatch:

name: book-deploy-build

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: renv-${{ hashFiles('renv.lock') }}
          restore-keys: renv-

      - name: Install packages
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Authenticate
        env:
          CONNECT_SERVER: https://beta.rstudioconnect.com/
          CONNECT_API_KEY: ${{ secrets.RSC_BETA_TOKEN }}
        run: |
          install.packages("rsconnect")
          rsconnect::addConnectServer(Sys.getenv("CONNECT_SERVER"), "RSC")
          rsconnect::connectApiUser(
            account = "GHA",
            server = "RSC",
            apiKey = Sys.getenv("CONNECT_API_KEY"))
        shell: Rscript {0}

      - name: Deploy Content
        env:
          CONTENT_ID: 14651
        run: |
          rsconnect::deploySite(
            appId = Sys.getenv("CONTENT_ID"),
            render = "server", logLevel = "verbose",
            forceUpdate = TRUE)
        shell: Rscript {0}
